ALTER TABLE "SHCLEARING"."HD_CENTDIS_ATTACHMENT" DROP CONSTRAINT "FK_CD_AT_BL" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN" DROP CONSTRAINT "FK_CD_BL_BI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL" DROP CONSTRAINT "FK_CD_BI_UW" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_ORGNAME" DROP CONSTRAINT "FK_CD_ORG_NAME" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INHERIT_REL" DROP CONSTRAINT "FK_CD_IR_BI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_CREDIT_REL" DROP CONSTRAINT "FK_CD_CR_BI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME" DROP CONSTRAINT "FK_CD_EXEST_EXE" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE" DROP CONSTRAINT "FK_CD_EXE_BI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATE_BOND" DROP CONSTRAINT "FK_CD_RB_BI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER" DROP CONSTRAINT "FK_CD_II_BI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATING_ORG" DROP CONSTRAINT "FK_CD_RO_ORG" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" DROP CONSTRAINT "FK_CD_BI_ORG_PUB" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" DROP CONSTRAINT "FK_CD_BI_ORG_INI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" DROP CONSTRAINT "FK_CD_BI_ORG_CUSTO" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" DROP CONSTRAINT "FK_CD_BI_ORG_MUW" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATE_BOND" DROP CONSTRAINT "FK_CD_RB_ORG" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATING_ORG" DROP CONSTRAINT "FK_CD_RO_AGENCY" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL" DROP CONSTRAINT "FK_CD_ORG_UW" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER" DROP CONSTRAINT "FK_CD_II_ORG" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_CREDIT_REL" DROP CONSTRAINT "FK_CD_CR_ORG" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INHERIT_REL" DROP CONSTRAINT "FK_CD_IR_ORG" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_PAYDAY" DROP CONSTRAINT "FK_CD_PD_BI" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_ORGTYPE" DROP CONSTRAINT "FK_CD_ORG_TYPE" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH" DROP CONSTRAINT "FK_CD_BP_BT" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG" DROP CONSTRAINT "FK_CD_BO_ORG" CASCADE;
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG" DROP CONSTRAINT "FK_CD_BO_BT" CASCADE;

DROP TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_ATTACHMENT" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_DCM" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_CHNLREL" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_ORGANIZATION" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_ORGNAME" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_INHERIT_REL" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_CREDIT_REL" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_RATING_ORG" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_RATE_BOND" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_ORGTYPE" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_LOG" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_PAYDAY" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_DCMLOG" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_DCMENUM" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_STATSCHART_DCMTYPE" CASCADE CONSTRAINTS;
DROP TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG" CASCADE CONSTRAINTS;

CREATE TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN" (
"SECURITYREPORTID" CHAR(32) NOT NULL,
"SECURITYALTID" CHAR(32) NULL,
"BULLETINCAPTION" VARCHAR2(200) NULL,
"BULLETINTYPECODE" VARCHAR2(5) NULL,
"DISCLOSUREINDOCATOR" CHAR(1) NULL,
"UPDATETIME" DATE NULL,
"DISCLOSURETYPE" CHAR(1) NULL,
"EVENTBULLETININDICATOR" CHAR(1) NULL,
"NOATTACHMENTS" NUMBER(2) NULL,
"PUBLISHINDICATOR" NUMBER(1) NULL,
"SENDINGTIME" TIMESTAMP(0) NULL,
"PUBLISHTIME" TIMESTAMP(0) NULL,
"CREATETIME" TIMESTAMP(0) NULL,
"PUBFAILEDTIME" NUMBER(1) NULL,
"LASTUPDATETIME" TIMESTAMP(0) NULL,
PRIMARY KEY ("SECURITYREPORTID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN" IS '集中信息披露-公告表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."SECURITYREPORTID" IS '披露ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."SECURITYALTID" IS '债券编号';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."BULLETINCAPTION" IS '公告标题';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."BULLETINTYPECODE" IS '公告类别编码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."DISCLOSUREINDOCATOR" IS '是否定时披露';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."UPDATETIME" IS '定时披露时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."DISCLOSURETYPE" IS '披露类型';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."EVENTBULLETININDICATOR" IS '是否为行权公告';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."NOATTACHMENTS" IS '附件个数';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."PUBLISHINDICATOR" IS '是否已发布(0-未发布,1-已发布,2-已撤销,3-定时待发布)';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."SENDINGTIME" IS '报文发送时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."PUBLISHTIME" IS '实际发布时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."CREATETIME" IS '首次创建时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."PUBFAILEDTIME" IS '发布失败次数, 发布成功时该值清零';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN"."LASTUPDATETIME" IS '最后更新时间';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_ATTACHMENT" (
"ATTACHMENTID" CHAR(32) NOT NULL,
"SECURITYREPORTID" CHAR(32) NOT NULL,
"ATTACHMENTTYPE" VARCHAR2(2) NULL,
"ATTACHMENTADDRESS" VARCHAR2(4000) NULL,
"ATTACHMENTNAME" VARCHAR2(255) NULL,
"ATTACHMENTSURNAME" VARCHAR2(32) NULL,
"ATTACHMENTSIZE" NUMBER NULL,
"FINANCIALREPORTYEAR" VARCHAR2(4) NULL,
PRIMARY KEY ("ATTACHMENTID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_ATTACHMENT" IS '集中信息披露-附件表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ATTACHMENT"."SECURITYREPORTID" IS '披露ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ATTACHMENT"."ATTACHMENTTYPE" IS '附件类型';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ATTACHMENT"."ATTACHMENTADDRESS" IS '附件地址';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ATTACHMENT"."ATTACHMENTNAME" IS '附件名称';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ATTACHMENT"."ATTACHMENTSURNAME" IS '附件后缀名';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ATTACHMENT"."ATTACHMENTSIZE" IS '文件大小';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ATTACHMENT"."FINANCIALREPORTYEAR" IS '财务报告年度';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" (
"SECURITYALTID" CHAR(32) NOT NULL,
"SECURITYID" CHAR(32) NULL,
"SYMBOL" VARCHAR2(200) NULL,
"FULLSYMBOL" VARCHAR2(200) NULL,
"SECURITYDESC" VARCHAR2(3) NULL,
"CURRENCY" VARCHAR2(3) NULL,
"CASHDATE" CHAR(8) NULL,
"SECURITYTERM" VARCHAR2(7) NULL,
"ISSUESIZEFORPLAN" NUMBER(25) NULL,
"MATURITYDATE" CHAR(8) NULL,
"ISSUEMETHOD" VARCHAR2(3) NULL,
"OFFERMETHOD" VARCHAR2(3) NULL,
"NUMBEROFISSUER" NUMBER(3) NULL,
"OPTIONELIGIBILITYINDICATOR" CHAR(1) NULL,
"ISSUEBEGINDATE" CHAR(8) NULL,
"ISSUERID" CHAR(32) NULL,
"PROMOTERID" CHAR(32) NULL,
"CUSTODIANID" CHAR(32) NULL,
"MAINUNDERWRITERID" CHAR(32) NULL,
"ISSUEDUEDATE" CHAR(8) NULL,
"PAYMENTDATE" CHAR(8) NULL,
"LASTUPDATETIME" TIMESTAMP(0) NULL,
PRIMARY KEY ("SECURITYALTID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" IS '集中信息披露-债券表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."SECURITYALTID" IS '债券编号';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."SECURITYID" IS '债券代码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."SYMBOL" IS '债券简称';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."FULLSYMBOL" IS '债券全称';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."SECURITYDESC" IS '债券类型编码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."CURRENCY" IS '币种';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."CASHDATE" IS '兑付日';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."SECURITYTERM" IS '期限';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."ISSUESIZEFORPLAN" IS '计划发行金额';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."MATURITYDATE" IS '到期日';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."ISSUEMETHOD" IS '发行方式';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."OFFERMETHOD" IS '招标方式';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."NUMBEROFISSUER" IS '集合债券发行人个数';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."OPTIONELIGIBILITYINDICATOR" IS '是否含权';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."ISSUEBEGINDATE" IS '发行起始日';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."ISSUERID" IS '发行人ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."PROMOTERID" IS '发起人ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."CUSTODIANID" IS '托管机构ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."MAINUNDERWRITERID" IS '簿记方主承机构ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."ISSUEDUEDATE" IS '发行截止日';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."PAYMENTDATE" IS '缴款日';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INSTRUMENT"."LASTUPDATETIME" IS '最后更新时间';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_DCM" (
"DCM_TYPE" VARCHAR2(64) NOT NULL,
"DCM_CODE" VARCHAR2(64) NOT NULL,
"DCM_DESC" VARCHAR2(256) NULL,
"CREATETIME" TIMESTAMP(0) NULL,
"UPDATETIME" TIMESTAMP(0) NULL,
"CREATOR" VARCHAR2(128) NULL,
"UPDATOR" VARCHAR2(128) NULL,
PRIMARY KEY ("DCM_TYPE", "DCM_CODE") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_DCM" IS '集中信息披露-基础定义表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCM"."DCM_TYPE" IS '数据类型(如债券类型)';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCM"."DCM_CODE" IS '数据代码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCM"."DCM_DESC" IS '描述';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCM"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCM"."UPDATETIME" IS '修改时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCM"."CREATOR" IS '导入人员';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCM"."UPDATOR" IS '修改人员';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_CHNLREL" (
"REL_ID" CHAR(32) NOT NULL,
"BULLETINTYPECODE" VARCHAR2(5) NOT NULL,
"CHANNELID" NUMBER(10) NOT NULL,
"CREATOR" VARCHAR2(100) NOT NULL,
"CREATETIME" TIMESTAMP(0) NOT NULL,
"SECURITYDESC" VARCHAR2(3) NULL,
PRIMARY KEY ("REL_ID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_CHNLREL" IS '集中信息披露-清算所网站栏目与二级公告类别关联关系表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CHNLREL"."REL_ID" IS '公告类别与栏目关联关系ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CHNLREL"."BULLETINTYPECODE" IS '二级公告类别编码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CHNLREL"."CHANNELID" IS 'WCM栏目ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CHNLREL"."CREATOR" IS '创建人';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CHNLREL"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CHNLREL"."SECURITYDESC" IS '债券类型';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_ORGANIZATION" (
"ORGID" CHAR(32) NOT NULL,
"ORGFULLNAME" VARCHAR2(200) NULL,
"ORGABBR" VARCHAR2(200) NULL,
"ORGCODE" VARCHAR2(36) NULL,
"ORGUNIONCODE" VARCHAR2(64) NULL,
"UPDATETIME" TIMESTAMP(0) NULL,
PRIMARY KEY ("ORGID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_ORGANIZATION" IS '集中信息披露-组织机构表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGANIZATION"."ORGFULLNAME" IS '机构全称';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGANIZATION"."ORGABBR" IS '机构简称';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGANIZATION"."ORGCODE" IS '组织机构代码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGANIZATION"."ORGUNIONCODE" IS '统一社会信用码(三证合一码)';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGANIZATION"."UPDATETIME" IS '最后更新时间';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL" (
"ORGID" CHAR(32) NOT NULL,
"SECURITYALTID" CHAR(32) NOT NULL,
PRIMARY KEY ("ORGID", "SECURITYALTID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL" IS '集中信息披露-联系主承及副主承关联表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL"."ORGID" IS '承销商ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL"."SECURITYALTID" IS '债券编码';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_ORGNAME" (
"NAMEID" CHAR(32) NOT NULL,
"ORGID" CHAR(32) NOT NULL,
"USEDNAME" VARCHAR2(200) NOT NULL,
"UPDATETIME" TIMESTAMP(0) NOT NULL,
"FIRSTBULLETINID" CHAR(32) NULL,
"LASTBULLETINID" CHAR(32) NULL,
PRIMARY KEY ("NAMEID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_ORGNAME" IS '集中信息披露-组织曾用名';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGNAME"."ORGID" IS '机构ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGNAME"."USEDNAME" IS '曾用名';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGNAME"."UPDATETIME" IS '录入系统时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGNAME"."FIRSTBULLETINID" IS '第一次录入该机构曾用名的公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGNAME"."LASTBULLETINID" IS '最后一次录入该机构曾用名的公告ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_INHERIT_REL" (
"SECURITYALTID" CHAR(32) NOT NULL,
"ORGID" CHAR(32) NOT NULL,
PRIMARY KEY ("SECURITYALTID", "ORGID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_INHERIT_REL" IS '集中清算平台-承继机构与债券关联表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INHERIT_REL"."SECURITYALTID" IS '机构代码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INHERIT_REL"."ORGID" IS '承继机构ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_CREDIT_REL" (
"SECURITYALTID" CHAR(32) NOT NULL,
"AGENCYID" CHAR(32) NOT NULL,
PRIMARY KEY ("SECURITYALTID", "AGENCYID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_CREDIT_REL" IS '集中信息披露-信用增进机构与债券关系表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CREDIT_REL"."SECURITYALTID" IS '债券编码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_CREDIT_REL"."AGENCYID" IS '信用增进机构ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE" (
"EXERCISEID" CHAR(32) NOT NULL,
"SECURITYALTID" CHAR(32) NOT NULL,
"EXERCISETYPE" VARCHAR2(4) NOT NULL,
"STRIKESTARTTIME" DATE NULL,
"UPDATETIME" TIMESTAMP(0) NULL,
"FIRSTBULLETINID" CHAR(32) NOT NULL,
"LASTBULLETINID" CHAR(32) NOT NULL,
PRIMARY KEY ("EXERCISEID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE" IS '集中信息披露-含权信息表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE"."EXERCISEID" IS '含权信息ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE"."SECURITYALTID" IS '债券ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE"."EXERCISETYPE" IS '含权种类';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE"."STRIKESTARTTIME" IS '首次行权日期';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE"."UPDATETIME" IS '更新时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE"."FIRSTBULLETINID" IS '首次加入的公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE"."LASTBULLETINID" IS '最后一次加入到公告ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME" (
"STRIKETIMEID" CHAR(32) NOT NULL,
"EXERCISEID" CHAR(32) NOT NULL,
"STRIKEDATE" DATE NOT NULL,
"UPDATETIME" TIMESTAMP(0) NULL,
"FIRSTBULLETINID" CHAR(32) NOT NULL,
"LASTBULLETINID" CHAR(32) NOT NULL,
PRIMARY KEY ("STRIKETIMEID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME" IS '集中信息披露-兑付日表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME"."STRIKETIMEID" IS '行权兑付日ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME"."EXERCISEID" IS '行权信息ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME"."STRIKEDATE" IS '行权日';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME"."UPDATETIME" IS '更新日期';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME"."FIRSTBULLETINID" IS '首次加入的公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME"."LASTBULLETINID" IS '最后一次加入的公告ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_RATING_ORG" (
"RATEID" CHAR(32) NOT NULL,
"AGENCYID" CHAR(32) NOT NULL,
"ISSUERID" CHAR(32) NOT NULL,
"RATETIME" CHAR(8) NULL,
"CREDITRATING" VARCHAR2(10) NULL,
"UPDATETIME" TIMESTAMP(0) NULL,
"FIRSTBULLETINID" CHAR(32) NOT NULL,
"LASTBULLETINID" CHAR(32) NOT NULL,
PRIMARY KEY ("RATEID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_RATING_ORG" IS '集中信息披露-主体评级结果';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATING_ORG"."AGENCYID" IS '评级机构ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATING_ORG"."ISSUERID" IS '主体ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATING_ORG"."RATETIME" IS '评级时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATING_ORG"."CREDITRATING" IS '评级结果';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATING_ORG"."UPDATETIME" IS '更新时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATING_ORG"."FIRSTBULLETINID" IS '第一次录入该条主体评级信息的公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATING_ORG"."LASTBULLETINID" IS '最后一次录入该条主体评级信息的公告ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_RATE_BOND" (
"RATEID" CHAR(32) NOT NULL,
"AGENCYID" CHAR(32) NOT NULL,
"SECURITYALTID" CHAR(32) NOT NULL,
"RATETIME" CHAR(8) NULL,
"CREDITRATING" VARCHAR2(10) NULL,
"UPDATETIME" TIMESTAMP(0) NOT NULL,
"FIRSTBULLETINID" CHAR(32) NOT NULL,
"LASTBULLETINID" CHAR(32) NOT NULL,
PRIMARY KEY ("RATEID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_RATE_BOND" IS '集中信息披露-债项评级';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATE_BOND"."AGENCYID" IS '评级机构ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATE_BOND"."SECURITYALTID" IS '债券编码';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATE_BOND"."RATETIME" IS '评级时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATE_BOND"."CREDITRATING" IS '评级结果';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATE_BOND"."UPDATETIME" IS '更新时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATE_BOND"."FIRSTBULLETINID" IS '首次加入的公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_RATE_BOND"."LASTBULLETINID" IS '最后一次加入的公告ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER" (
"ORGID" CHAR(32) NOT NULL,
"SECURITYALTID" CHAR(32) NOT NULL,
PRIMARY KEY ("ORGID", "SECURITYALTID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER" IS '集中信息披露-单个发行人';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER"."SECURITYALTID" IS '债券ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_ORGTYPE" (
"TYPEID" CHAR(32) NOT NULL,
"ORGID" CHAR(32) NOT NULL,
"ORGTYPE" VARCHAR2(3) NOT NULL,
PRIMARY KEY ("TYPEID") 
);

COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGTYPE"."TYPEID" IS '机构类型ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGTYPE"."ORGID" IS '机构ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_ORGTYPE"."ORGTYPE" IS '机构类型';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_LOG" (
"LOGID" CHAR(32) NOT NULL,
"LOGTYPE" CHAR(1) NULL,
"SOURCETYPE" CHAR(1) NULL,
"OPERATOR" VARCHAR2(128) NULL,
"IMPORTTIME" TIMESTAMP(0) NULL,
"IMPORTRESULT" CHAR(1) NULL,
"BULLETINID" CHAR(32) NULL,
"IMPORTFILENAME" VARCHAR2(512) NULL,
"ERRORMSG" VARCHAR2(1024) NULL,
PRIMARY KEY ("LOGID") 
);

COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."LOGID" IS '日志ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."LOGTYPE" IS '日志类型(0-新增,1-修改,2-自动发布,3-手动发布,4-定时发布,5-撤销)';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."SOURCETYPE" IS '导入操作来源(0-自动导入,1-应急导入)';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."OPERATOR" IS '操作人员';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."IMPORTTIME" IS '导入时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."IMPORTRESULT" IS '导入结果(0-成功,1-失败)';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."BULLETINID" IS '对应公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."IMPORTFILENAME" IS '应急导入文件名称';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_LOG"."ERRORMSG" IS '错误信息';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_PAYDAY" (
"PAYDAYID" CHAR(32) NOT NULL,
"SECURITYALTID" CHAR(32) NOT NULL,
"COUPONPAYMENTDATE" DATE NOT NULL,
"CREATETIME" TIMESTAMP(0) NOT NULL,
"FIRSTBULLETINID" CHAR(32) NOT NULL,
"LASTBULLETINID" CHAR(32) NOT NULL,
PRIMARY KEY ("PAYDAYID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_PAYDAY" IS '集中信息披露-付息日表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_PAYDAY"."PAYDAYID" IS '付息日ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_PAYDAY"."SECURITYALTID" IS '债券编号';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_PAYDAY"."COUPONPAYMENTDATE" IS '付息日';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_PAYDAY"."CREATETIME" IS '创建时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_PAYDAY"."FIRSTBULLETINID" IS '第一次录入该付息日信息的公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_PAYDAY"."LASTBULLETINID" IS '最后一次录入该付息日信息的公告ID';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_DCMLOG" (
"DCMLOGID" CHAR(32) NOT NULL,
"LOGMESSAGE" VARCHAR2(1024) NOT NULL,
"IMPORTTIME" TIMESTAMP(0) NOT NULL,
"OPERATOR" VARCHAR2(100) NOT NULL,
"LOGTYPE" CHAR(1) NOT NULL,
PRIMARY KEY ("DCMLOGID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_DCMLOG" IS '集中信息披露-导入日志表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMLOG"."DCMLOGID" IS '导入日志ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMLOG"."LOGMESSAGE" IS '日志内容';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMLOG"."IMPORTTIME" IS '导入时间';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMLOG"."OPERATOR" IS '导入人员';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMLOG"."LOGTYPE" IS '日志类型(0-DCM导入,1-机构导入)';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_DCMENUM" (
"DCM_TYPE" VARCHAR2(64) NOT NULL,
"DCM_CODE" VARCHAR2(64) NULL,
"DCM_DESC" VARCHAR2(64) NULL,
PRIMARY KEY ("DCM_TYPE") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_DCMENUM" IS '集中信息披露-DCM类型及类型对应的字段表头枚举关系表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMENUM"."DCM_TYPE" IS 'DCM类型';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMENUM"."DCM_CODE" IS 'DCM数据代码(表头1)';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_DCMENUM"."DCM_DESC" IS 'DCM数据描述(表头2)';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH" (
"PUBLISHID" CHAR(32) NOT NULL,
"BULLETINID" CHAR(32) NOT NULL,
"WCMDOCID" NUMBER(10) NOT NULL,
"WCMCHNLID" NUMBER(10) NOT NULL,
"PUBLISHTIME" TIMESTAMP(0) NOT NULL,
PRIMARY KEY ("PUBLISHID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH" IS '集中信息披露-公告发布信息表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH"."PUBLISHID" IS '发布ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH"."BULLETINID" IS '公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH"."WCMDOCID" IS '发布后的WCM文章ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH"."WCMCHNLID" IS '发布到的栏目ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH"."PUBLISHTIME" IS '实际发布时间';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_STATSCHART_DCMTYPE" (
"ID" CHAR(32) NOT NULL,
"DCM_TYPE" VARCHAR2(64) NOT NULL,
"DCM_CODE" VARCHAR2(64) NOT NULL,
PRIMARY KEY ("ID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_STATSCHART_DCMTYPE" IS '统计需要显示的DCM类别信息表';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_STATSCHART_DCMTYPE"."ID" IS '统计需要显示的DCM类别信息';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_STATSCHART_DCMTYPE"."DCM_TYPE" IS '相应的DCM类型';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_STATSCHART_DCMTYPE"."DCM_CODE" IS '需要显示的DCMCODE';

CREATE TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG" (
"ID" CHAR(32) NOT NULL,
"BULLETINID" CHAR(32) NOT NULL,
"ORGID" CHAR(32) NOT NULL,
"ORGTYPE" VARCHAR2(3) NOT NULL,
PRIMARY KEY ("ID") 
);

COMMENT ON TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG" IS '用于记录公告与机构关系';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG"."ID" IS '主键';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG"."BULLETINID" IS '公告ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG"."ORGID" IS '机构ID';
COMMENT ON COLUMN "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG"."ORGTYPE" IS '所涉及的机构类型';


ALTER TABLE "SHCLEARING"."HD_CENTDIS_ATTACHMENT" ADD CONSTRAINT "FK_CD_AT_BL" FOREIGN KEY ("SECURITYREPORTID") REFERENCES "SHCLEARING"."HD_CENTDIS_BULLETIN" ("SECURITYREPORTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN" ADD CONSTRAINT "FK_CD_BL_BI" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL" ADD CONSTRAINT "FK_CD_BI_UW" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_ORGNAME" ADD CONSTRAINT "FK_CD_ORG_NAME" FOREIGN KEY ("ORGID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INHERIT_REL" ADD CONSTRAINT "FK_CD_IR_BI" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_CREDIT_REL" ADD CONSTRAINT "FK_CD_CR_BI" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE_STRIKETIME" ADD CONSTRAINT "FK_CD_EXEST_EXE" FOREIGN KEY ("EXERCISEID") REFERENCES "SHCLEARING"."HD_CENTDIS_EXERCISE" ("EXERCISEID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_EXERCISE" ADD CONSTRAINT "FK_CD_EXE_BI" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATE_BOND" ADD CONSTRAINT "FK_CD_RB_BI" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER" ADD CONSTRAINT "FK_CD_II_BI" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATING_ORG" ADD CONSTRAINT "FK_CD_RO_ORG" FOREIGN KEY ("ISSUERID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ADD CONSTRAINT "FK_CD_BI_ORG_PUB" FOREIGN KEY ("ISSUERID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ADD CONSTRAINT "FK_CD_BI_ORG_INI" FOREIGN KEY ("PROMOTERID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ADD CONSTRAINT "FK_CD_BI_ORG_CUSTO" FOREIGN KEY ("CUSTODIANID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ADD CONSTRAINT "FK_CD_BI_ORG_MUW" FOREIGN KEY ("MAINUNDERWRITERID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATE_BOND" ADD CONSTRAINT "FK_CD_RB_ORG" FOREIGN KEY ("AGENCYID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_RATING_ORG" ADD CONSTRAINT "FK_CD_RO_AGENCY" FOREIGN KEY ("AGENCYID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_UDERWRITER_REL" ADD CONSTRAINT "FK_CD_ORG_UW" FOREIGN KEY ("ORGID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INDIVIDUALISSUER" ADD CONSTRAINT "FK_CD_II_ORG" FOREIGN KEY ("ORGID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_CREDIT_REL" ADD CONSTRAINT "FK_CD_CR_ORG" FOREIGN KEY ("AGENCYID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_INHERIT_REL" ADD CONSTRAINT "FK_CD_IR_ORG" FOREIGN KEY ("ORGID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_PAYDAY" ADD CONSTRAINT "FK_CD_PD_BI" FOREIGN KEY ("SECURITYALTID") REFERENCES "SHCLEARING"."HD_CENTDIS_INSTRUMENT" ("SECURITYALTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_ORGTYPE" ADD CONSTRAINT "FK_CD_ORG_TYPE" FOREIGN KEY ("ORGID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_PUBLISH" ADD CONSTRAINT "FK_CD_BP_BT" FOREIGN KEY ("BULLETINID") REFERENCES "SHCLEARING"."HD_CENTDIS_BULLETIN" ("SECURITYREPORTID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG" ADD CONSTRAINT "FK_CD_BO_ORG" FOREIGN KEY ("ORGID") REFERENCES "SHCLEARING"."HD_CENTDIS_ORGANIZATION" ("ORGID");
ALTER TABLE "SHCLEARING"."HD_CENTDIS_BULLETIN_ORG" ADD CONSTRAINT "FK_CD_BO_BT" FOREIGN KEY ("BULLETINID") REFERENCES "SHCLEARING"."HD_CENTDIS_BULLETIN" ("SECURITYREPORTID");

