/**
删除表
 */
DROP TABLE SHCLEARING.HD_MEETING_PINCODE CASCADE CONSTRAINTS;
COMMIT;
/**
删除表数据
 */
/**
TRUNCATE TABLE shclearing.HD_MEETING_PINCODE;
 */

/**
添加对于的列以及注释
 */
ALTER TABLE HD_MEETING DROP COLUMN PINCODE_NUM;
ALTER TABLE HD_MEETING DROP COLUMN ADVICE_PINCODE_NUM;
ALTER TABLE HD_MEETING ADD (PINCODE_NUM NUMBER(10) DEFAULT 0);
ALTER TABLE HD_MEETING ADD (ADVICE_PINCODE_NUM NUMBER(10) DEFAULT 0);
ALTER TABLE HD_MEETING_ATTENDER MODIFY (OPERATOR VARCHAR2(40 BYTE) );
ALTER TABLE HD_MEETING_ATTENDER MODIFY (CREATOR VARCHAR2(40 BYTE) );


ALTER TABLE HD_MEETING_FEEDBACK MODIFY (CREATOR VARCHAR2(40 BYTE) );
ALTER TABLE HD_MEETING_FEEDBACK MODIFY (OPERATOR VARCHAR2(40 BYTE) );

ALTER TABLE HD_MEETING_FEEDBACK_TRACE MODIFY (CREATOR VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_FEEDBACK_TRACE MODIFY (OPERATOR VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_FEEDBACK_TRACE MODIFY (FEEDBACK_SUBMITER VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_FEEDBACK_STATUS  MODIFY (CREATOR VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_FEEDBACK_STATUS  MODIFY (OPERATOR VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_FEEDBACK_STATUS  MODIFY (FEEDBACK_SUBMITER VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_ATTENDER_TRACE   MODIFY (FEEDBACK_SUBMITER VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_ATTENDER_TRACE   MODIFY (OPERATOR VARCHAR2(32 BYTE) );
ALTER TABLE HD_MEETING_ATTENDER_TRACE   MODIFY (CREATOR VARCHAR2(32 BYTE) );

ALTER TABLE HD_MEETING_FEEDBACK_TRACE ADD (SUBMIT_NAME VARCHAR2(40) DEFAULT NULL );
ALTER TABLE HD_MEETING_FEEDBACK_TRACE MODIFY (SUBMIT_NAME VARCHAR2(40) DEFAULT NULL );
COMMIT;
COMMENT ON COLUMN HD_MEETING.PINCODE_NUM IS '登录码总数';
COMMENT ON COLUMN HD_MEETING.ADVICE_PINCODE_NUM IS '已经反馈的非注册用户总数';
COMMENT ON COLUMN HD_MEETING_FEEDBACK_TRACE.SUBMIT_NAME IS '非注册用户反馈者姓名';
COMMIT;
/*
建立相关索引
*/
CREATE INDEX FEEDBACK_STATUS_CREATOR ON HD_MEETING_FEEDBACK_STATUS (CREATOR);
CREATE INDEX FEEDBACK_STATUS_MEETING_ID ON HD_MEETING_FEEDBACK_STATUS (MEETING_ID);
CREATE INDEX FEEDBACK_STATUS_CRTIME ON HD_MEETING_FEEDBACK_STATUS (CRTIME);

COMMIT;


CREATE TABLE SHCLEARING.HD_MEETING_PINCODE
(
  PIN_CODE              CHAR(32) NOT NULL PRIMARY KEY,

  PIN_CODE_ORG_FULLNAME VARCHAR2(150),

  ORG_SHORTNAME         VARCHAR2(50),

  SUBMIT_NAME           VARCHAR2(100),

  SUBMIT_MOBILE         VARCHAR2(50),

  SUBMIT_TELEPHONE      VARCHAR2(50),

  SUBMIT_EMAIL          VARCHAR2(100),

  MEETING_ID            CHAR(32),

  FEEDBACK_URL          VARCHAR2(200),

  IS_FEED_BACK          VARCHAR2(9) DEFAULT 0,

  STATUS                VARCHAR2(9),

  CRTIME                VARCHAR2(50),

  FEEDBACK_TIME         VARCHAR2(50),

  LAST_FEEDBACK_TIME    VARCHAR2(50),

  TAG                   CHAR(32)

);


COMMENT ON COLUMN HD_MEETING_PINCODE.PIN_CODE IS '非注册用户登录码';
COMMENT ON COLUMN HD_MEETING_PINCODE.PIN_CODE_ORG_FULLNAME IS '反馈机构全称';
COMMENT ON COLUMN HD_MEETING_PINCODE.ORG_SHORTNAME IS '反馈机构简称';
COMMENT ON COLUMN HD_MEETING_PINCODE.SUBMIT_NAME IS '反馈提交人姓名';
COMMENT ON COLUMN HD_MEETING_PINCODE.SUBMIT_MOBILE IS '反馈提交人手机';
COMMENT ON COLUMN HD_MEETING_PINCODE.SUBMIT_TELEPHONE IS '反馈提交人电话';
COMMENT ON COLUMN HD_MEETING_PINCODE.SUBMIT_EMAIL IS '反馈提交人Email';
COMMENT ON COLUMN HD_MEETING_PINCODE.MEETING_ID IS '反馈提交会议主键ID';
COMMENT ON COLUMN HD_MEETING_PINCODE.FEEDBACK_URL IS '反馈链接URL';
COMMENT ON COLUMN HD_MEETING_PINCODE.IS_FEED_BACK IS '是否第一次反馈 default 0 ,1 反馈过';
COMMENT ON COLUMN HD_MEETING_PINCODE.STATUS IS '验证码是否有效。1.正常，2.注销，3.锁定 ';
COMMENT ON COLUMN HD_MEETING_PINCODE.CRTIME IS '创建时间';
COMMENT ON COLUMN HD_MEETING_PINCODE.FEEDBACK_TIME IS '第一次反馈时间';
COMMENT ON COLUMN HD_MEETING_PINCODE.LAST_FEEDBACK_TIME IS '最后一次反馈时间';
COMMENT ON COLUMN HD_MEETING_PINCODE.TAG IS '一批验证码的标志位';

ALTER TABLE HD_MEETING_PINCODE ADD CONSTRAINT PINCODE_MEETINGID_UNIQUE UNIQUE
  (PIN_CODE, MEETING_ID)
ENABLE;

CREATE INDEX HD_MEETING_PINCODE_INDEX ON HD_MEETING_PINCODE (MEETING_ID, PIN_CODE);
COMMIT;
ALTER TABLE HD_MEETING_FEEDBACK_TRACE MODIFY (SUBMIT_NAME VARCHAR2(40) DEFAULT NULL );

ALTER TABLE HD_MEETING_ATTENDER MODIFY (ATTENDER_NAME VARCHAR2(40 BYTE) );

ALTER TABLE HD_MEETING_ATTENDER MODIFY (DEPT VARCHAR2(100 BYTE) );

ALTER TABLE HD_MEETING_ATTENDER MODIFY (DUTY VARCHAR2(100 BYTE) );

ALTER TABLE HD_MEETING_ATTENDER MODIFY (DINING_REMARK VARCHAR2(200 BYTE) );
ALTER TABLE HD_MEETING_ATTENDER MODIFY (REMARK VARCHAR2(1000 BYTE) );
ALTER TABLE HD_MEETING_ATTENDER MODIFY (TRAFFIC_OTHER VARCHAR2(200 BYTE) );
COMMIT;



